/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaprueba;

import java.awt.Color;

/**
 *
 * @author anki0
 */
public class Hoteleria extends javax.swing.JFrame {

    int xM, yM;
    
    public Hoteleria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Background = new javax.swing.JPanel();
        BarrraVertical = new javax.swing.JPanel();
        jpSalida = new javax.swing.JPanel();
        jlSalida = new javax.swing.JLabel();
        jpHuesped = new javax.swing.JPanel();
        jlHuesped = new javax.swing.JLabel();
        jpHabitacion = new javax.swing.JPanel();
        jlHabitacion = new javax.swing.JLabel();
        jpReserva = new javax.swing.JPanel();
        jlRserva = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PanelMovil = new javax.swing.JPanel();
        Escritorio = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 760));
        setResizable(false);

        Background.setBackground(new java.awt.Color(204, 204, 204));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarrraVertical.setBackground(new java.awt.Color(204, 51, 0));

        jpSalida.setBackground(new java.awt.Color(255, 51, 0));
        jpSalida.setForeground(new java.awt.Color(255, 255, 255));

        jlSalida.setBackground(new java.awt.Color(255, 255, 255));
        jlSalida.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jlSalida.setForeground(new java.awt.Color(255, 255, 255));
        jlSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSalida.setText("SALIR");
        jlSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlSalidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlSalidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlSalidaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpSalidaLayout = new javax.swing.GroupLayout(jpSalida);
        jpSalida.setLayout(jpSalidaLayout);
        jpSalidaLayout.setHorizontalGroup(
            jpSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlSalida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
        );
        jpSalidaLayout.setVerticalGroup(
            jpSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jpHuesped.setBackground(new java.awt.Color(204, 51, 0));

        jlHuesped.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jlHuesped.setForeground(new java.awt.Color(255, 153, 102));
        jlHuesped.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlHuesped.setText("Huespedes");
        jlHuesped.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlHuesped.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlHuespedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlHuespedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlHuespedMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpHuespedLayout = new javax.swing.GroupLayout(jpHuesped);
        jpHuesped.setLayout(jpHuespedLayout);
        jpHuespedLayout.setHorizontalGroup(
            jpHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlHuesped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpHuespedLayout.setVerticalGroup(
            jpHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlHuesped, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        jpHabitacion.setBackground(new java.awt.Color(204, 51, 0));

        jlHabitacion.setBackground(new java.awt.Color(255, 102, 51));
        jlHabitacion.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jlHabitacion.setForeground(new java.awt.Color(255, 153, 102));
        jlHabitacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlHabitacion.setText("Habitaciones");
        jlHabitacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlHabitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlHabitacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlHabitacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlHabitacionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpHabitacionLayout = new javax.swing.GroupLayout(jpHabitacion);
        jpHabitacion.setLayout(jpHabitacionLayout);
        jpHabitacionLayout.setHorizontalGroup(
            jpHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpHabitacionLayout.setVerticalGroup(
            jpHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jpReserva.setBackground(new java.awt.Color(204, 51, 0));

        jlRserva.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jlRserva.setForeground(new java.awt.Color(255, 153, 102));
        jlRserva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlRserva.setText("Reservas");
        jlRserva.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlRserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlRservaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlRservaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlRservaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpReservaLayout = new javax.swing.GroupLayout(jpReserva);
        jpReserva.setLayout(jpReservaLayout);
        jpReservaLayout.setHorizontalGroup(
            jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlRserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpReservaLayout.setVerticalGroup(
            jpReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlRserva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imags/Lines.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BarrraVerticalLayout = new javax.swing.GroupLayout(BarrraVertical);
        BarrraVertical.setLayout(BarrraVerticalLayout);
        BarrraVerticalLayout.setHorizontalGroup(
            BarrraVerticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpHuesped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BarrraVerticalLayout.createSequentialGroup()
                .addGroup(BarrraVerticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BarrraVerticalLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jpSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BarrraVerticalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        BarrraVerticalLayout.setVerticalGroup(
            BarrraVerticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarrraVerticalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(102, 102, 102)
                .addComponent(jpHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)
                .addComponent(jpSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        Background.add(BarrraVertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 770));

        PanelMovil.setBackground(new java.awt.Color(204, 204, 204));
        PanelMovil.setForeground(new java.awt.Color(204, 204, 204));
        PanelMovil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelMovil.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelMovilMouseDragged(evt);
            }
        });
        PanelMovil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelMovilMousePressed(evt);
            }
        });

        javax.swing.GroupLayout PanelMovilLayout = new javax.swing.GroupLayout(PanelMovil);
        PanelMovil.setLayout(PanelMovilLayout);
        PanelMovilLayout.setHorizontalGroup(
            PanelMovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        PanelMovilLayout.setVerticalGroup(
            PanelMovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        Background.add(PanelMovil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        Escritorio.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Cambria", 1, 58)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Bienvenido");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imags/izq.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imags/der.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(476, Short.MAX_VALUE))
        );

        Background.add(Escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 800, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanelMovilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMovilMousePressed
        xM = evt.getX();
        yM= evt.getY();
        
    }//GEN-LAST:event_PanelMovilMousePressed

    private void PanelMovilMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMovilMouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x- xM, y- yM);
    }//GEN-LAST:event_PanelMovilMouseDragged

    private void jlSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalidaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jlSalidaMouseClicked

    private void jlSalidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalidaMouseEntered
        jpSalida.setBackground(new Color(255,153,102));
        jlSalida.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_jlSalidaMouseEntered

    private void jlSalidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalidaMouseExited
        jpSalida.setBackground(Color.red);
        jlSalida.setForeground(new Color (255,255,255));
    }//GEN-LAST:event_jlSalidaMouseExited

    private void jlHabitacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlHabitacionMouseEntered
        jpHabitacion.setBackground(Color.red);
        jlHabitacion.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_jlHabitacionMouseEntered

    private void jlHabitacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlHabitacionMouseExited
        jpHabitacion.setBackground(new Color (204,51,0));
        jlHabitacion.setForeground(new Color (255,153,102));
    }//GEN-LAST:event_jlHabitacionMouseExited

    private void jlRservaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRservaMouseEntered
        jpReserva.setBackground(Color.red);
        jlRserva.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_jlRservaMouseEntered

    private void jlRservaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRservaMouseExited
        jpReserva.setBackground(new Color (204,51,0));
        jlRserva.setForeground(new Color (255,153,102));
    }//GEN-LAST:event_jlRservaMouseExited

    private void jlHuespedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlHuespedMouseExited
        jpHuesped.setBackground(new Color (204,51,0));
        jlHuesped.setForeground(new Color (255,153,102));
    }//GEN-LAST:event_jlHuespedMouseExited

    private void jlHuespedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlHuespedMouseEntered
        jpHuesped.setBackground(Color.red);
        jlHuesped.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_jlHuespedMouseEntered

    private void jlHuespedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlHuespedMouseClicked
        Escritorio.removeAll();
        Escritorio.repaint();
        ifHuesped ifH= new ifHuesped();
        ifH.setVisible(true);
        ifH.getContentPane().setBackground(Color.DARK_GRAY);
        Escritorio.add(ifH);
            
    }//GEN-LAST:event_jlHuespedMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Escritorio.removeAll();
        Escritorio.repaint();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jlHabitacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlHabitacionMouseClicked
        Escritorio.removeAll();
        Escritorio.repaint();
        ifHabitacion ifHa= new ifHabitacion();
        ifHa.setVisible(true);
        ifHa.getContentPane().setBackground(Color.DARK_GRAY);
        Escritorio.add(ifHa);
    }//GEN-LAST:event_jlHabitacionMouseClicked

    private void jlRservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRservaMouseClicked
        Escritorio.removeAll();
        Escritorio.repaint();
        ifReserva ifR= new ifReserva();
        ifR.setVisible(true);
        ifR.getContentPane().setBackground(Color.DARK_GRAY);
        Escritorio.add(ifR);
    }//GEN-LAST:event_jlRservaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hoteleria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hoteleria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hoteleria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hoteleria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hoteleria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel BarrraVertical;
    private javax.swing.JPanel Escritorio;
    private javax.swing.JPanel PanelMovil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlHabitacion;
    private javax.swing.JLabel jlHuesped;
    private javax.swing.JLabel jlRserva;
    private javax.swing.JLabel jlSalida;
    private javax.swing.JPanel jpHabitacion;
    private javax.swing.JPanel jpHuesped;
    private javax.swing.JPanel jpReserva;
    private javax.swing.JPanel jpSalida;
    // End of variables declaration//GEN-END:variables
}
